server {
    server_name localhost;
    root /srv/public;

    location / {
        try_files $uri /index.html;
    }

    error_log /var/log/nginx/cv_error.log;
    access_log /var/log/nginx/cv_access.log;
}